version: '3.9'

services:
  flask_app:
    build: .
    container_name: resume_processor
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: always
